targets:
  $default:
    sources:
      - $package$
      - pubspec.yaml
      - lib/**
      - test/**
#    builders:
#      json_serializable:
#        enabled: true
#        generate_for:
#          include:
#            - lib/src/feature/**/*.codegen.dart
#        options:
#          any_map: false
#          checked: false
#          create_factory: true
#          create_to_json: true
#          disallow_unrecognized_keys: false
#          explicit_to_json: true
#          field_rename: none
#          ignore_unannotated: false
#          include_if_null: true
#          #nullable: true
#      pubspec_generator:
#        options:
#          output: lib/src/common/constant/pubspec.yaml.g.dart